### PR TITLE
feat: add item filter by title

### PR DESCRIPTION
**Pull request by ed-paredes**
Add  logic to filter a item by title

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Lovely. Let me take a look.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Umm… something is not quite right, please take another look and try again.

**Review by ed-paredes — COMMENTED** [review]
chore: review changes

**Review by vanessa-cooper — APPROVED** [review]
Looking good! Now we can move on to the UI. 
I'll send you more details on Snack.

**Pull request merged**
